### ISSUE TITLE
Text to read as a list

### ISSUE THREAD

**Issue by TrickyTroll** [TrickyTroll/good-bot#7]
## The problem

Things to read are currently defined as one string per scene. A user can only define what to read as one big chunk of text. This makes it quite hard to say time the text to read and the content that is being recorded.

## The solution

The text to read should be defined as a list of strings instead of a string. During the configuration splitting, each string in the list will be written to its own file. Google TTS is [priced per character](https://cloud.google.com/text-to-speech/pricing) anyway.

When assembling the video each `mp3` file will be rendered with the corresponding command. The configuration file would look something like this:

```
1:
  - commands:
      - echo 'hello world'
    expect:
      - prompt
    read:
			- Hello, world.

  - commands:
      - ls -a
    expect:
      - prompt
    read: 
			- I can run commands.
2:
  - commands:
      - echo 'hello from another scene'
    expect:
      - prompt
    read:
			- Here is a new scene!
3:
  - commands:
      - echo 'I can also be quiet...sometimes'
    expect:
      - prompt
```

**Comment by TrickyTroll** [comment]
## Closing the issue

Good Bot won't be using a `list` of `read` arguments for now. To read multiple things in one scene, a user can just create multiple `commands` objects in one scene.

```
1:
  - commands:
      - echo 'hello world'
    expect:
      - prompt
    read:
      - Hello, world.

  - commands:
      - ls -a
    expect:
      - prompt
    read: 
      - I can run commands.
```

For example, in this sample, Good Bot will read `Hello, world.` while typing the `echo 'hello world'` command, and then read `I can run commands` while using the `ls` command.

Synchronizing the audio with the commands would require the user to input more information in their configuration file. The config file already seems complicated enough.
